
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzinvgbpabcwkfddflpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6aW52Z2JwYWJjd2tmZGRmbHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MDU1ODksImV4cCI6MjA1NTM4MTU4OX0.7h2UyY3B7GYQ6MbCdS0oLPDg4BYIolEBdgSILBrY31Q";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    persistSession: true
  }
});
